name: Dev Deploy Lambda

on:
  push:
    branches: [ main ]
    paths:
      - 'src/user-info/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '18'

    # - name: Install dependencies
    #   run: npm install

    #  - name: Run tests
    #    run: npm test

    # - name: Build
    #   run: npm run build

    - name: Install zip tool
      uses: montudor/action-zip@v1
      
    - name: Create deployment package
      run: |
           cd src/user-info
           zip -r ../../user-info.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://code.zip
          
          
on:
  push:
    branches: [ main ]
    paths:
      - 'src/lambda-profile/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '18'

    # - name: Install dependencies
    #   run: npm install

    #  - name: Run tests
    #    run: npm test

    # - name: Build
    #   run: npm run build

    - name: Install zip tool
      uses: montudor/action-zip@v1
      
    - name: Create deployment package
      run: |
           cd src/lambda-profile
           zip -r ../../lambda-profile.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://code.zip