name: Dev Deploy Lambda

on:
  push:
    branches: [ main ]
    paths:
      - 'src/user-info/**'
      - 'src/lambda-profile/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      userInfo: ${{ steps.filter.outputs.user-info }}
      lambdaProfile: ${{ steps.filter.outputs.lambda-profile }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          user-info:
            - 'src/user-info/**'
          lambda-profile:
            - 'src/lambda-profile/**'

  deployUserInfo:
    needs: changes
    if: ${{ needs.changes.outputs.userInfo == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install zip tool
      uses: montudor/action-zip@v1
      
    - name: Create deployment package
      run: |
           cd src/user-info
           zip -r ../../user-info.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ secrets.USER_INFO_LAMBDA_NAME }} \
          --zip-file fileb://user-info.zip

  deployLambdaProfile:
    needs: changes
    if: ${{ needs.changes.outputs.lambdaProfile == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install zip tool
      uses: montudor/action-zip@v1
      
    - name: Create deployment package
      run: |
           cd src/lambda-profile
           zip -r ../../lambda-profile.zip .

    - name: Configure AWS credentialss
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_PROFILE_NAME }} \
          --zip-file fileb://lambda-profile.zip